### ISSUE TITLE
Memory leak with hash in version 2.0011

### ISSUE THREAD

**Issue by sestaton** [robkinyon/dbm-deep#11]
I have discovered a memory leak in the latest version when trying to use a tied hash. After simplifying the code, I see the same behavior with a simple key/value store, and this behavior is seen with the OO interface or a tied hash.

It should be easy to replicate. For reference, I posted this question on [StackOverflow](http://stackoverflow.com/q/29659224/1543853) and someone commented that they could also replicate this issue. I could provide more information if needed.

**Comment by sestaton** [comment]
Here is a simple example to demonstrate the leak:

    use strict;
    use warnings;
    use DBM::Deep;
 
    my $dbm = "does_leak.dbm";
    my $db  = DBM::Deep->new( $dbm );
    open my $list, '-|', 'cat /usr/share/dict/words'
        or die $!;

    while (my $word = <$list>) {
        chomp $word;
        $db->{$word} = 1;
    }
    close $list;

I found no memory cycles with Devel::Cycle or Test::Memory::Cycle, but there is clearly a leak somewhere. Sorry I can't offer solution right now but I will take a look at the code.

**Comment by robkinyon** [comment]
Okay, so the amount of RAM does go up over time. I put your code from `open my $list, ...` to the end within a `while (1)` loop to see it go up. On my system (Ubuntu 14.04, perl 5.22.0), it went up by about 1k for every 30k words read. (Unscientifically just watching `top`.)

My immediate guess is that this is the amount of RAM being used by the DBM::Deep objects keeping that keep track of everything. While it would be ideal that the RAM would be completely stable, I'm going to call this "Not a bug". If you can give me something that I can put in a .t file, then I would be delighted to work on this.

**Comment by sestaton** [comment]
One problem I see with creating a test file is having to load the data, unless it's created in the test, but if you are okay with the dictionary I used above I can create a test for this case. 

To elaborate on the issue, if I use a tied hash and SQLite, I do not observe the memory usage increasing. I can load a very large file and the memory usage never gets above ~220k RAM whereas I can observe DBM::Deep using >30Gb RAM on the same data. And, it will continue to increase while data is being read. That looks like a classic memory leak to me, and I would expect the behavior similar to the SQLite interface, which is to allocate a certain amount for the objects, then continue writing the data to the disk. Am I wrong in these expectations?

I'll create a test script to demonstrate even if it's something that can't be included as a test script. This module is super useful and I hope I can help. Thanks.
