### ISSUE TITLE
Fail gracefully when database hits max size

### ISSUE THREAD

**Issue by Pascal666** [robkinyon/dbm-deep#24]
Original bug report: https://rt.cpan.org/Public/Bug/Display.html?id=130395

Problem still exists in 2.0017, so re-opening on Github as directed.

Maximum database size is determined by pack_size when the database is created.  Currently, when the database gets too big it gets corrupted and programs using the database yield various random errors.  It would be nice if DBM::Deep would fail gracefully when the database hits its maximum size, yielding an error message like "Database full: recreate using larger pack_size".

Code to reproduce:
```
require DBM::Deep;

my $filename = 'test.db';

DBM::Deep->new(
    file      => $filename,
    pack_size => 'small',
);

tie my %db, 'DBM::Deep', $filename;

for (0..99999) {
    $db{$_} = $_;
}
```

Output from the above:
```
[root@perltest DBM]# ./pack_size.pl
DBM::Deep: Cannot read sector at 4598 in get_bucket_list() at ./pack_size.pl line 18
[root@perltest DBM]# ./pack_size.pl
DBM::Deep: '161': Don't know what to do with type '▒' at ./pack_size.pl line 18
[root@perltest DBM]# ./pack_size.pl
Can't call method "free" on an undefined value at /usr/local/share/perl5/5.32/DBM/Deep/Sector/File/Reference.pm line 152.
```

**Comment by DrHyde** [comment]
Sorry for pointing at the wrong repo! This one is no longer in use, I've copied the issue over to https://github.com/DBM-Deep/DBM-Deep/issues/2

**Comment by Pascal666** [comment]
Bug fixed in new repository.
